version: '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis

    orderdb:
        image: mcr.microsoft.com/mssql/server

    rabbitmq:
        image: rabbitmq:3-management-alpine

    order.api:
        image: ${DOCKER_REGISTRY-}orderapi
        build:
            context: .
            dockerfile: containers/Order.Api/Dockerfile

    order.consumer:
        image: ${DOCKER_REGISTRY-}orderconsumer
        build:
            context: .
            dockerfile: containers/Order.Consumer/Dockerfile
            
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: containers/Catalog.Api/Dockerfile
            
    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: containers/Basket.Api/Dockerfile
            
    apigateway:
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: containers/Api.Gateway/Dockerfile
            
    webapp:
        image: ${DOCKER_REGISTRY-}webapp
        build:
            context: .
            dockerfile: containers/Web.App/Dockerfile
